# make sure to install all necessary packages
---
- hosts: vminstance
  become: yes
  tasks:
    - name: Update and upgrade system packages
      package:
        name: '*'
        state: latest
      register: update_status

    - name: Ensure firewall is configured
      ufw:
        state: enabled
        policy: allow

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install packages for HTTP, Git, Docker, and Python toolchain
      apt:
        name: 
          - nginx  
          - git
          - docker.io
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - libssl-dev
        state: present