# short ansible script to create a GCP VM instance
---
- name: Create instance in GCP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a disk 
      google.cloud.gcp_compute_disk: 
        name: "{{ disk_name }}" 
        size_gb: "{{ disk_size }}" 
        source_image: "{{ source_image }}" 
        zone: "{{ zone }}" 
        project: "{{ project }}" 
        auth_kind: serviceaccount 
        service_account_file: "{{ service_account_file }}" 
        state: present
      register: disk
    - name: Create a Network
      google.cloud.gcp_compute_network:
        name: network-instance
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        auto_create_subnetworks: true
        state: present
      register: network
    - name: Create an Address
      google.cloud.gcp_compute_address:
        name: address-instance
        region: us-central1
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: present
      register: address
    - name: Create an Instance
      gcp_compute_instance:
        auth_kind: serviceaccount
        project: "{{ project }}"
        service_account_file: "{{ service_account_file }}"
        state: present
        name: "{{ machine_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT